name: Question
description: General question or request for clarification.
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: "Describe clearly"
    validations:
      required: true
